title Spectrometer Controller Operation

[*] --> Integrate : Begin integration sequence
state "Integration Phase" as Integrate {
    Position : Position of spectrometer
    note bottom of Position
        Implicitly known by motor (speed / time)
    end note
    Data : Spectral data array
    Integrate --> Integrate : Integration not complete

}
state "Post-Processing Phase" as Process {
    Integrate --> Cleanup : End Integration
    Cleanup -> Average : Filtered data
    note bottom of Cleanup 
        Perform cosine similarity on 
        spectra data to throw out 
        non-plant data
    end note
    Average : Average values of Spectral integration
    Average --> [*] : Save Spectra to drive
    
}
state "Motor Driver (TB6600)" as Motor
Motor : Moves the spectrometer along the rail
Integrate -left-> Motor : Move to next position
'Motor -right-> Integrate : Position
Integrate -down-> Spectrometer : Scan Signal
Spectrometer -up-> Integrate : Spectral intensities

Average --> Server : Complete Spectra
